apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-c
          image: kdanjana/todoapp:v3
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              value: "asd"
            - name: MYSQL_PASSWORD
              value: "123"

            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_PORT
              value: "3306"
          command: ["/bin/bash","-c"]
          args:
            - python manage.py makemigrations;
              python manage.py migrate;
              python manage.py runserver 0.0.0.0:8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      nodePort: 30007
      targetPort: 8000
      port: 8000